version: '3.8'

services:

  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8081"
    command:
      - 'php'
      - '-S'
      - '[::]:8081'
      - '-t'
      - '/var/www/html'

volumes:
  pg: